def exception_test(passed_list):
    num_store = []
    for num in passed_list:
        num_store.append(num)
        if num == num - 1
    # whatever += passed_list

user_nums = raw_input('Enter a series of numbers between 1 and 10 >> ')
exception_test(user_nums)


def exceptions():
    assert([1, 2, 3, 4])
    assert([1, 2, 3])
    assert([1, 3, 4])
    assert([4, 5, 7, 2])